export const APP_COLOR = {
    PRIMARY_BLUE: "#2F50C1",
    TEXT_INPUT: "#F4F2F8",
    PLACEHOLDER_TEXT: "#A7A3B3",
    REGULAR_TEXT: '#757281',
    DARK_TEXT: "#58536E",
    HEADER_COLOR: "#4561DB",
    BOX_BG: '#F4F2F8',

    RECIEVED_BG: "#D9E6FD",
    RECIEVED_TEXT: "#2F50C1",

    CANCELLED_BG: '#F4F2F8',
    CANCELLED_TEXT: "#58536E",

    ERROR_BG: "#FEE3D4",
    ERROR_TEXT: "#D12030",

    DELIVRY_BG: "#E3FAD6",
    DELIVERY_TEXT: "#208D28",

    PUTAWAY_BG: "#FFF3D5",
    PUTAWAY_TEXT: "#DB7E21",

    STROKE_COLOR: "#6E91EC"
}
export type ShipmentStatus =
    | 'RECEIVED'
    | 'CANCELED'
    | 'ERROR'
    | 'DELIVERED'
    | 'PUT AWAY'
    | 'REJECTED'
    | 'LOST'
    | 'ON HOLD';


export const statusColors: Partial<Record<ShipmentStatus, string>> = {
    RECEIVED: APP_COLOR.RECIEVED_TEXT,
    CANCELED: APP_COLOR.CANCELLED_TEXT,
    ERROR: APP_COLOR.ERROR_TEXT,
    DELIVERED: APP_COLOR.DELIVERY_TEXT,
    'PUT AWAY': APP_COLOR.PUTAWAY_TEXT,
    REJECTED: APP_COLOR.ERROR_TEXT,
    LOST: APP_COLOR.ERROR_TEXT,
    'ON HOLD': APP_COLOR.PUTAWAY_TEXT,

};

export const statusBGColors: Partial<Record<ShipmentStatus, string>> = {
    RECEIVED: APP_COLOR.RECIEVED_BG,
    CANCELED: APP_COLOR.CANCELLED_BG,
    ERROR: APP_COLOR.ERROR_BG,
    DELIVERED: APP_COLOR.DELIVRY_BG,
    'PUT AWAY': APP_COLOR.PUTAWAY_BG,
    REJECTED: APP_COLOR.ERROR_BG,
    LOST: APP_COLOR.ERROR_BG,
    'ON HOLD': APP_COLOR.PUTAWAY_BG,
};
